categories:
  - multimedia
  - hello kitty
  - moebel
  - haushalt
  - bekleidung
  - sport
  - gartengeraete
  - kostueme
  - kleidung
  - haustier kostueme
  - haustier accessoires
  - geraet
  - bau
  - beauty
  - kind
  - utensilien
  - pc accessoires
  - zuege
  - textilien
  - kueche
  - schatten
  - spielzeug
  - tier
  - roboter
  - kakao
  - technik
  - kuechengeraete
  - quadrat
  - Parfum
  - Lebensmittel
  - Bierbauch
  - Sex
  - Schuhe
  - Fußpilz
  - Trinkspiel
  - LEGO Star Wars
  - Scheiße
  - Heimwerker
  - Fortnite

# relative to article-element
paths:
    brand: .//li[contains(@class, 'find_tile')]//p[@class='find_tile__brand']
    name: .//li[contains(@class, 'find_tile')]//p[contains(@class,'find_tile__name')]
    link: .//li[contains(@class, 'find_tile')]//a[contains(@class,'find_tile__productLink')]
    original_price: .//li[contains(@class, 'find_tile')]//span[contains(@class,'find_tile__priceValue--strikethrough')]
    price: .//li[contains(@class, 'find_tile')]//span[contains(@class,'find_tile__priceValue')]
    img: .//li[contains(@class, 'find_tile')]//img[contains(@class,'find_tile__productImage')]
db:
    link: link to db
    password: password to db

